### ISSUE TITLE
not parsing right

### ISSUE THREAD

**Issue by CodeEagle** [nixzhu/Baby#4]
Briefly describe your problem when use Baby.
```
        let comment: Comment????????????????????????
        let ref: Any?????????????
        let refType: String????????????
        let masterBranch: String????????????
        let description: String????????????
        let pusherType: String????????????
```

JSON String

```
[{"id":"6228926947","type":"WatchEvent","actor":{"id":4371178,"login":"msching","display_login":"msching","gravatar_id":"","url":"https://api.github.com/users/msching","avatar_url":"https://avatars.githubusercontent.com/u/4371178?"},"repo":{"id":95496672,"name":"weichsel/ZIPFoundation","url":"https://api.github.com/repos/weichsel/ZIPFoundation"},"payload":{"action":"started"},"public":true,"created_at":"2017-07-11T01:28:22Z"},{"id":"6227592957","type":"WatchEvent","actor":{"id":51363,"login":"0xced","display_login":"0xced","gravatar_id":"","url":"https://api.github.com/users/0xced","avatar_url":"https://avatars.githubusercontent.com/u/51363?"},"repo":{"id":35160657,"name":"canton7/RestEase","url":"https://api.github.com/repos/canton7/RestEase"},"payload":{"action":"started"},"public":true,"created_at":"2017-07-10T21:06:35Z"},{"id":"6224298602","type":"WatchEvent","actor":{"id":219689,"login":"lexrus","display_login":"lexrus","gravatar_id":"","url":"https://api.github.com/users/lexrus","avatar_url":"https://avatars.githubusercontent.com/u/219689?"},"repo":{"id":91767095,"name":"tidwall/pinhole","url":"https://api.github.com/repos/tidwall/pinhole"},"payload":{"action":"started"},"public":true,"created_at":"2017-07-10T13:59:19Z"},{"id":"6224291375","type":"WatchEvent","actor":{"id":219689,"login":"lexrus","display_login":"lexrus","gravatar_id":"","url":"https://api.github.com/users/lexrus","avatar_url":"https://avatars.githubusercontent.com/u/219689?"},"repo":{"id":96056297,"name":"mmcloughlin/globe","url":"https://api.github.com/repos/mmcloughlin/globe"},"payload":{"action":"started"},"public":true,"created_at":"2017-07-10T13:58:29Z"},{"id":"6223878618","type":"IssueCommentEvent","actor":{"id":15805487,"login":"commando24","display_login":"commando24","gravatar_id":"","url":"https://api.github.com/users/commando24","avatar_url":"https://avatars.githubusercontent.com/u/15805487?"},"repo":{"id":2514500,"name":"muhku/FreeStreamer","url":"https://api.github.com/repos/muhku/FreeStreamer"},"payload":{"action":"created","issue":{"url":"https://api.github.com/repos/muhku/FreeStreamer/issues/222","repository_url":"https://api.github.com/repos/muhku/FreeStreamer","labels_url":"https://api.github.com/repos/muhku/FreeStreamer/issues/222/labels{/name}","comments_url":"https://api.github.com/repos/muhku/FreeStreamer/issues/222/comments","events_url":"https://api.github.com/repos/muhku/FreeStreamer/issues/222/events","html_url":"https://github.com/muhku/FreeStreamer/issues/222","id":117599839,"number":222,"title":"audioStream play/pause problem","user":{"login":"blackmatch","id":12443954,"avatar_url":"https://avatars0.githubusercontent.com/u/12443954?v=3","gravatar_id":"","url":"https://api.github.com/users/blackmatch","html_url":"https://github.com/blackmatch","followers_url":"https://api.github.com/users/blackmatch/followers","following_url":"https://api.github.com/users/blackmatch/following{/other_user}","gists_url":"https://api.github.com/users/blackmatch/gists{/gist_id}","starred_url":"https://api.github.com/users/blackmatch/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/blackmatch/subscriptions","organizations_url":"https://api.github.com/users/blackmatch/orgs","repos_url":"https://api.github.com/users/blackmatch/repos","events_url":"https://api.github.com/users/blackmatch/events{/privacy}","received_events_url":"https://api.github.com/users/blackmatch/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2015-11-18T14:37:39Z","updated_at":"2017-07-10T13:05:24Z","closed_at":"2016-02-07T06:54:55Z","body":"when I call the function [audioStream play], I need to call the function [audioStream pause] twice, then the music pause.Then need to call the function [audioStream play] twice, music play.\n"},"comment":{"url":"https://api.github.com/repos/muhku/FreeStreamer/issues/comments/314099289","html_url":"https://github.com/muhku/FreeStreamer/issues/222#issuecomment-314099289","issue_url":"https://api.github.com/repos/muhku/FreeStreamer/issues/222","id":314099289,"user":{"login":"commando24","id":15805487,"avatar_url":"https://avatars0.githubusercontent.com/u/15805487?v=3","gravatar_id":"","url":"https://api.github.com/users/commando24","html_url":"https://github.com/commando24","followers_url":"https://api.github.com/users/commando24/followers","following_url":"https://api.github.com/users/commando24/following{/other_user}","gists_url":"https://api.github.com/users/commando24/gists{/gist_id}","starred_url":"https://api.github.com/users/commando24/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/commando24/subscriptions","organizations_url":"https://api.github.com/users/commando24/orgs","repos_url":"https://api.github.com/users/commando24/repos","events_url":"https://api.github.com/users/commando24/events{/privacy}","received_events_url":"https://api.github.com/users/commando24/received_events","type":"User","site_admin":false},"created_at":"2017-07-10T13:05:24Z","updated_at":"2017-07-10T13:05:24Z","body":"I am still facing this issue in version 3.7.3. @muhku please look into this."}},"public":true,"created_at":"2017-07-10T13:05:24Z"},{"id":"6223367359","type":"WatchEvent","actor":{"id":51363,"login":"0xced","display_login":"0xced","gravatar_id":"","url":"https://api.github.com/users/0xced","avatar_url":"https://avatars.githubusercontent.com/u/51363?"},"repo":{"id":30097856,"name":"anagram4wander/VirtualizingObservableCollection","url":"https://api.github.com/repos/anagram4wander/VirtualizingObservableCollection"},"payload":{"action":"started"},"public":true,"created_at":"2017-07-10T11:43:33Z"},{"id":"6222697154","type":"WatchEvent","actor":{"id":4371178,"login":"msching","display_login":"msching","gravatar_id":"","url":"https://api.github.com/users/msching","avatar_url":"https://avatars.githubusercontent.com/u/4371178?"},"repo":{"id":84387539,"name":"efremidze/Magnetic","url":"https://api.github.com/repos/efremidze/Magnetic"},"payload":{"action":"started"},"public":true,"created_at":"2017-07-10T09:48:26Z"},{"id":"6222696635","type":"WatchEvent","actor":{"id":4371178,"login":"msching","display_login":"msching","gravatar_id":"","url":"https://api.github.com/users/msching","avatar_url":"https://avatars.githubusercontent.com/u/4371178?"},"repo":{"id":84908257,"name":"Ronnel/BubblePicker","url":"https://api.github.com/repos/Ronnel/BubblePicker"},"payload":{"action":"started"},"public":true,"created_at":"2017-07-10T09:48:21Z"},{"id":"6221966105","type":"WatchEvent","actor":{"id":219689,"login":"lexrus","display_login":"lexrus","gravatar_id":"","url":"https://api.github.com/users/lexrus","avatar_url":"https://avatars.githubusercontent.com/u/219689?"},"repo":{"id":95798441,"name":"athityakumar/colorls","url":"https://api.github.com/repos/athityakumar/colorls"},"payload":{"action":"started"},"public":true,"created_at":"2017-07-10T07:49:10Z"},{"id":"6221942601","type":"WatchEvent","actor":{"id":219689,"login":"lexrus","display_login":"lexrus","gravatar_id":"","url":"https://api.github.com/users/lexrus","avatar_url":"https://avatars.githubusercontent.com/u/219689?"},"repo":{"id":74459010,"name":"zalando/SwiftMonkey","url":"https://api.github.com/repos/zalando/SwiftMonkey"},"payload":{"action":"started"},"public":true,"created_at":"2017-07-10T07:44:36Z","org":{"id":1564818,"login":"zalando","gravatar_id":"","url":"https://api.github.com/orgs/zalando","avatar_url":"https://avatars.githubusercontent.com/u/1564818?"}},{"id":"6221307348","type":"WatchEvent","actor":{"id":2911921,"login":"ChenYilong","display_login":"ChenYilong","gravatar_id":"","url":"https://api.github.com/users/ChenYilong","avatar_url":"https://avatars.githubusercontent.com/u/2911921?"},"repo":{"id":93403131,"name":"artemnovichkov/iOS-11-by-Examples","url":"https://api.github.com/repos/artemnovichkov/iOS-11-by-Examples"},"payload":{"action":"started"},"public":true,"created_at":"2017-07-10T04:57:09Z"},{"id":"6219453878","type":"ForkEvent","actor":{"id":10682908,"login":"coderyi","display_login":"coderyi","gravatar_id":"","url":"https://api.github.com/users/coderyi","avatar_url":"https://avatars.githubusercontent.com/u/10682908?"},"repo":{"id":95652496,"name":"olucurious/awesome-arkit","url":"https://api.github.com/repos/olucurious/awesome-arkit"},"payload":{"forkee":{"id":96687559,"name":"awesome-arkit","full_name":"coderyi/awesome-arkit","owner":{"login":"coderyi","id":10682908,"avatar_url":"https://avatars0.githubusercontent.com/u/10682908?v=3","gravatar_id":"","url":"https://api.github.com/users/coderyi","html_url":"https://github.com/coderyi","followers_url":"https://api.github.com/users/coderyi/followers","following_url":"https://api.github.com/users/coderyi/following{/other_user}","gists_url":"https://api.github.com/users/coderyi/gists{/gist_id}","starred_url":"https://api.github.com/users/coderyi/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/coderyi/subscriptions","organizations_url":"https://api.github.com/users/coderyi/orgs","repos_url":"https://api.github.com/users/coderyi/repos","events_url":"https://api.github.com/users/coderyi/events{/privacy}","received_events_url":"https://api.github.com/users/coderyi/received_events","type":"User","site_admin":false},"private":false,"html_url":"https://github.com/coderyi/awesome-arkit","description":"A curated list of awesome ARKit projects and resources. Feel free to contribute!","fork":true,"url":"https://api.github.com/repos/coderyi/awesome-arkit","forks_url":"https://api.github.com/repos/coderyi/awesome-arkit/forks","keys_url":"https://api.github.com/repos/coderyi/awesome-arkit/keys{/key_id}","collaborators_url":"https://api.github.com/repos/coderyi/awesome-arkit/collaborators{/collaborator}","teams_url":"https://api.github.com/repos/coderyi/awesome-arkit/teams","hooks_url":"https://api.github.com/repos/coderyi/awesome-arkit/hooks","issue_events_url":"https://api.github.com/repos/coderyi/awesome-arkit/issues/events{/number}","events_url":"https://api.github.com/repos/coderyi/awesome-arkit/events","assignees_url":"https://api.github.com/repos/coderyi/awesome-arkit/assignees{/user}","branches_url":"https://api.github.com/repos/coderyi/awesome-arkit/branches{/branch}","tags_url":"https://api.github.com/repos/coderyi/awesome-arkit/tags","blobs_url":"https://api.github.com/repos/coderyi/awesome-arkit/git/blobs{/sha}","git_tags_url":"https://api.github.com/repos/coderyi/awesome-arkit/git/tags{/sha}","git_refs_url":"https://api.github.com/repos/coderyi/awesome-arkit/git/refs{/sha}","trees_url":"https://api.github.com/repos/coderyi/awesome-arkit/git/trees{/sha}","statuses_url":"https://api.github.com/repos/coderyi/awesome-arkit/statuses/{sha}","languages_url":"https://api.github.com/repos/coderyi/awesome-arkit/languages","stargazers_url":"https://api.github.com/repos/coderyi/awesome-arkit/stargazers","contributors_url":"https://api.github.com/repos/coderyi/awesome-arkit/contributors","subscribers_url":"https://api.github.com/repos/coderyi/awesome-arkit/subscribers","subscription_url":"https://api.github.com/repos/coderyi/awesome-arkit/subscription","commits_url":"https://api.github.com/repos/coderyi/awesome-arkit/commits{/sha}","git_commits_url":"https://api.github.com/repos/coderyi/awesome-arkit/git/commits{/sha}","comments_url":"https://api.github.com/repos/coderyi/awesome-arkit/comments{/number}","issue_comment_url":"https://api.github.com/repos/coderyi/awesome-arkit/issues/comments{/number}","contents_url":"https://api.github.com/repos/coderyi/awesome-arkit/contents/{+path}","compare_url":"https://api.github.com/repos/coderyi/awesome-arkit/compare/{base}...{head}","merges_url":"https://api.github.com/repos/coderyi/awesome-arkit/merges","archive_url":"https://api.github.com/repos/coderyi/awesome-arkit/{archive_format}{/ref}","downloads_url":"https://api.github.com/repos/coderyi/awesome-arkit/downloads","issues_url":"https://api.github.com/repos/coderyi/awesome-arkit/issues{/number}","pulls_url":"https://api.github.com/repos/coderyi/awesome-arkit/pulls{/number}","milestones_url":"https://api.github.com/repos/coderyi/awesome-arkit/milestones{/number}","notifications_url":"https://api.github.com/repos/coderyi/awesome-arkit/notifications{?since,all,participating}","labels_url":"https://api.github.com/repos/coderyi/awesome-arkit/labels{/name}","releases_url":"https://api.github.com/repos/coderyi/awesome-arkit/releases{/id}","deployments_url":"https://api.github.com/repos/coderyi/awesome-arkit/deployments","created_at":"2017-07-09T13:54:36Z","updated_at":"2017-07-09T13:40:40Z","pushed_at":"2017-07-05T16:19:53Z","git_url":"git://github.com/coderyi/awesome-arkit.git","ssh_url":"git@github.com:coderyi/awesome-arkit.git","clone_url":"https://github.com/coderyi/awesome-arkit.git","svn_url":"https://github.com/coderyi/awesome-arkit","homepage":null,"size":868,"stargazers_count":0,"watchers_count":0,"language":null,"has_issues":false,"has_projects":true,"has_downloads":true,"has_wiki":true,"has_pages":false,"forks_count":0,"mirror_url":null,"open_issues_count":0,"forks":0,"open_issues":0,"watchers":0,"default_branch":"master","public":true}},"public":true,"created_at":"2017-07-09T13:54:36Z"},{"id":"6218999125","type":"WatchEvent","actor":{"id":5144674,"login":"0x5e","display_login":"0x5e","gravatar_id":"","url":"https://api.github.com/users/0x5e","avatar_url":"https://avatars.githubusercontent.com/u/5144674?"},"repo":{"id":7369087,"name":"swisspol/GCDWebServer","url":"https://api.github.com/repos/swisspol/GCDWebServer"},"payload":{"action":"started"},"public":true,"created_at":"2017-07-09T08:59:18Z"},{"id":"6218985900","type":"ForkEvent","actor":{"id":1287724,"login":"zhuhaow","display_login":"zhuhaow","gravatar_id":"","url":"https://api.github.com/users/zhuhaow","avatar_url":"https://avatars.githubusercontent.com/u/1287724?"},"repo":{"id":39840932,"name":"google/googletest","url":"https://api.github.com/repos/google/googletest"},"payload":{"forkee":{"id":96672205,"name":"googletest","full_name":"zhuhaow/googletest","owner":{"login":"zhuhaow","id":1287724,"avatar_url":"https://avatars1.githubusercontent.com/u/1287724?v=3","gravatar_id":"","url":"https://api.github.com/users/zhuhaow","html_url":"https://github.com/zhuhaow","followers_url":"https://api.github.com/users/zhuhaow/followers","following_url":"https://api.github.com/users/zhuhaow/following{/other_user}","gists_url":"https://api.github.com/users/zhuhaow/gists{/gist_id}","starred_url":"https://api.github.com/users/zhuhaow/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/zhuhaow/subscriptions","organizations_url":"https://api.github.com/users/zhuhaow/orgs","repos_url":"https://api.github.com/users/zhuhaow/repos","events_url":"https://api.github.com/users/zhuhaow/events{/privacy}","received_events_url":"https://api.github.com/users/zhuhaow/received_events","type":"User","site_admin":false},"private":false,"html_url":"https://github.com/zhuhaow/googletest","description":"Google Test","fork":true,"url":"https://api.github.com/repos/zhuhaow/googletest","forks_url":"https://api.github.com/repos/zhuhaow/googletest/forks","keys_url":"https://api.github.com/repos/zhuhaow/googletest/keys{/key_id}","collaborators_url":"https://api.github.com/repos/zhuhaow/googletest/collaborators{/collaborator}","teams_url":"https://api.github.com/repos/zhuhaow/googletest/teams","hooks_url":"https://api.github.com/repos/zhuhaow/googletest/hooks","issue_events_url":"https://api.github.com/repos/zhuhaow/googletest/issues/events{/number}","events_url":"https://api.github.com/repos/zhuhaow/googletest/events","assignees_url":"https://api.github.com/repos/zhuhaow/googletest/assignees{/user}","branches_url":"https://api.github.com/repos/zhuhaow/googletest/branches{/branch}","tags_url":"https://api.github.com/repos/zhuhaow/googletest/tags","blobs_url":"https://api.github.com/repos/zhuhaow/googletest/git/blobs{/sha}","git_tags_url":"https://api.github.com/repos/zhuhaow/googletest/git/tags{/sha}","git_refs_url":"https://api.github.com/repos/zhuhaow/googletest/git/refs{/sha}","trees_url":"https://api.github.com/repos/zhuhaow/googletest/git/trees{/sha}","statuses_url":"https://api.github.com/repos/zhuhaow/googletest/statuses/{sha}","languages_url":"https://api.github.com/repos/zhuhaow/googletest/languages","stargazers_url":"https://api.github.com/repos/zhuhaow/googletest/stargazers","contributors_url":"https://api.github.com/repos/zhuhaow/googletest/contributors","subscribers_url":"https://api.github.com/repos/zhuhaow/googletest/subscribers","subscription_url":"https://api.github.com/repos/zhuhaow/googletest/subscription","commits_url":"https://api.github.com/repos/zhuhaow/googletest/commits{/sha}","git_commits_url":"https://api.github.com/repos/zhuhaow/googletest/git/commits{/sha}","comments_url":"https://api.github.com/repos/zhuhaow/googletest/comments{/number}","issue_comment_url":"https://api.github.com/repos/zhuhaow/googletest/issues/comments{/number}","contents_url":"https://api.github.com/repos/zhuhaow/googletest/contents/{+path}","compare_url":"https://api.github.com/repos/zhuhaow/googletest/compare/{base}...{head}","merges_url":"https://api.github.com/repos/zhuhaow/googletest/merges","archive_url":"https://api.github.com/repos/zhuhaow/googletest/{archive_format}{/ref}","downloads_url":"https://api.github.com/repos/zhuhaow/googletest/downloads","issues_url":"https://api.github.com/repos/zhuhaow/googletest/issues{/number}","pulls_url":"https://api.github.com/repos/zhuhaow/googletest/pulls{/number}","milestones_url":"https://api.github.com/repos/zhuhaow/googletest/milestones{/number}","notifications_url":"https://api.github.com/repos/zhuhaow/googletest/notifications{?since,all,participating}","labels_url":"https://api.github.com/repos/zhuhaow/googletest/labels{/name}","releases_url":"https://api.github.com/repos/zhuhaow/googletest/releases{/id}","deployments_url":"https://api.github.com/repos/zhuhaow/googletest/deployments","created_at":"2017-07-09T08:50:11Z","updated_at":"2017-07-09T04:36:22Z","pushed_at":"2017-07-08T16:00:10Z","git_url":"git://github.com/zhuhaow/googletest.git","ssh_url":"git@github.com:zhuhaow/googletest.git","clone_url":"https://github.com/zhuhaow/googletest.git","svn_url":"https://github.com/zhuhaow/googletest","homepage":"","size":3010,"stargazers_count":0,"watchers_count":0,"language":null,"has_issues":false,"has_projects":true,"has_downloads":false,"has_wiki":false,"has_pages":false,"forks_count":0,"mirror_url":null,"open_issues_count":0,"forks":0,"open_issues":0,"watchers":0,"default_branch":"master","public":true}},"public":true,"created_at":"2017-07-09T08:50:11Z","org":{"id":1342004,"login":"google","gravatar_id":"","url":"https://api.github.com/orgs/google","avatar_url":"https://avatars.githubusercontent.com/u/1342004?"}},{"id":"6218895508","type":"WatchEvent","actor":{"id":10682908,"login":"coderyi","display_login":"coderyi","gravatar_id":"","url":"https://api.github.com/users/coderyi","avatar_url":"https://avatars.githubusercontent.com/u/10682908?"},"repo":{"id":93403131,"name":"artemnovichkov/iOS-11-by-Examples","url":"https://api.github.com/repos/artemnovichkov/iOS-11-by-Examples"},"payload":{"action":"started"},"public":true,"created_at":"2017-07-09T07:48:47Z"},{"id":"6218566105","type":"WatchEvent","actor":{"id":435208,"login":"nixzhu","display_login":"nixzhu","gravatar_id":"","url":"https://api.github.com/users/nixzhu","avatar_url":"https://avatars.githubusercontent.com/u/435208?"},"repo":{"id":96159807,"name":"kishikawakatsumi/BookReader","url":"https://api.github.com/repos/kishikawakatsumi/BookReader"},"payload":{"action":"started"},"public":true,"created_at":"2017-07-09T03:25:23Z"},{"id":"6218247516","type":"WatchEvent","actor":{"id":1019875,"login":"onevcat","display_login":"onevcat","gravatar_id":"","url":"https://api.github.com/users/onevcat","avatar_url":"https://avatars.githubusercontent.com/u/1019875?"},"repo":{"id":96223912,"name":"onevcat/github-battle","url":"https://api.github.com/repos/onevcat/github-battle"},"payload":{"action":"started"},"public":true,"created_at":"2017-07-08T23:05:55Z"},{"id":"6218129069","type":"WatchEvent","actor":{"id":1542751,"login":"xxxAIRINxxx","display_login":"xxxAIRINxxx","gravatar_id":"","url":"https://api.github.com/users/xxxAIRINxxx","avatar_url":"https://avatars.githubusercontent.com/u/1542751?"},"repo":{"id":95981267,"name":"DingdingKim/CoinNow","url":"https://api.github.com/repos/DingdingKim/CoinNow"},"payload":{"action":"started"},"public":true,"created_at":"2017-07-08T21:45:27Z"},{"id":"6217345727","type":"CreateEvent","actor":{"id":5144674,"login":"0x5e","display_login":"0x5e","gravatar_id":"","url":"https://api.github.com/users/0x5e","avatar_url":"https://avatars.githubusercontent.com/u/5144674?"},"repo":{"id":96622914,"name":"0x5e/DLNACast","url":"https://api.github.com/repos/0x5e/DLNACast"},"payload":{"ref":null,"ref_type":"repository","master_branch":"master","description":"DLNA screen mirror application in macOS.(In progress)","pusher_type":"user"},"public":true,"created_at":"2017-07-08T14:10:26Z"},{"id":"6217324278","type":"WatchEvent","actor":{"id":5144674,"login":"0x5e","display_login":"0x5e","gravatar_id":"","url":"https://api.github.com/users/0x5e","avatar_url":"https://avatars.githubusercontent.com/u/5144674?"},"repo":{"id":70739248,"name":"cherezov/dlnap","url":"https://api.github.com/repos/cherezov/dlnap"},"payload":{"action":"started"},"public":true,"created_at":"2017-07-08T13:58:11Z"},{"id":"6217239974","type":"WatchEvent","actor":{"id":160165,"login":"wildthink","display_login":"wildthink","gravatar_id":"","url":"https://api.github.com/users/wildthink","avatar_url":"https://avatars.githubusercontent.com/u/160165?"},"repo":{"id":92369115,"name":"CodeEagle/ATML","url":"https://api.github.com/repos/CodeEagle/ATML"},"payload":{"action":"started"},"public":true,"created_at":"2017-07-08T13:04:08Z"},{"id":"6216906308","type":"WatchEvent","actor":{"id":10682908,"login":"coderyi","display_login":"coderyi","gravatar_id":"","url":"https://api.github.com/users/coderyi","avatar_url":"https://avatars.githubusercontent.com/u/10682908?"},"repo":{"id":8180848,"name":"libimobiledevice/ideviceinstaller","url":"https://api.github.com/repos/libimobiledevice/ideviceinstaller"},"payload":{"action":"started"},"public":true,"created_at":"2017-07-08T09:18:33Z","org":{"id":3584568,"login":"libimobiledevice","gravatar_id":"","url":"https://api.github.com/orgs/libimobiledevice","avatar_url":"https://avatars.githubusercontent.com/u/3584568?"}},{"id":"6216401122","type":"WatchEvent","actor":{"id":435208,"login":"nixzhu","display_login":"nixzhu","gravatar_id":"","url":"https://api.github.com/users/nixzhu","avatar_url":"https://avatars.githubusercontent.com/u/435208?"},"repo":{"id":94761104,"name":"jknthn/core-ml-demo","url":"https://api.github.com/repos/jknthn/core-ml-demo"},"payload":{"action":"started"},"public":true,"created_at":"2017-07-08T03:22:16Z"},{"id":"6212695294","type":"WatchEvent","actor":{"id":1019875,"login":"onevcat","display_login":"onevcat","gravatar_id":"","url":"https://api.github.com/users/onevcat","avatar_url":"https://avatars.githubusercontent.com/u/1019875?"},"repo":{"id":83999700,"name":"sdmg15/Best-websites-a-programmer-should-visit","url":"https://api.github.com/repos/sdmg15/Best-websites-a-programmer-should-visit"},"payload":{"action":"started"},"public":true,"created_at":"2017-07-07T14:44:11Z"},{"id":"6211853540","type":"IssuesEvent","actor":{"id":15805487,"login":"commando24","display_login":"commando24","gravatar_id":"","url":"https://api.github.com/users/commando24","avatar_url":"https://avatars.githubusercontent.com/u/15805487?"},"repo":{"id":2514500,"name":"muhku/FreeStreamer","url":"https://api.github.com/repos/muhku/FreeStreamer"},"payload":{"action":"opened","issue":{"url":"https://api.github.com/repos/muhku/FreeStreamer/issues/362","repository_url":"https://api.github.com/repos/muhku/FreeStreamer","labels_url":"https://api.github.com/repos/muhku/FreeStreamer/issues/362/labels{/name}","comments_url":"https://api.github.com/repos/muhku/FreeStreamer/issues/362/comments","events_url":"https://api.github.com/repos/muhku/FreeStreamer/issues/362/events","html_url":"https://github.com/muhku/FreeStreamer/issues/362","id":241252841,"number":362,"title":"issue with playItem method of FSAudioController","user":{"login":"commando24","id":15805487,"avatar_url":"https://avatars0.githubusercontent.com/u/15805487?v=3","gravatar_id":"","url":"https://api.github.com/users/commando24","html_url":"https://github.com/commando24","followers_url":"https://api.github.com/users/commando24/followers","following_url":"https://api.github.com/users/commando24/following{/other_user}","gists_url":"https://api.github.com/users/commando24/gists{/gist_id}","starred_url":"https://api.github.com/users/commando24/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/commando24/subscriptions","organizations_url":"https://api.github.com/users/commando24/orgs","repos_url":"https://api.github.com/users/commando24/repos","events_url":"https://api.github.com/users/commando24/events{/privacy}","received_events_url":"https://api.github.com/users/commando24/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2017-07-07T12:44:12Z","updated_at":"2017-07-07T12:44:12Z","closed_at":null,"body":"I am streaming some urls using \r\n`play(fromPlaylist: playlist, itemIndex: 0)\r\n`\r\nmethod and i am using this below method to change next or previous songs.\r\n`- (void)playItemAtIndex:(NSUInteger)index\r\n`\r\nbut everytime i use above method i get this below error\r\n**[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.**\r\n I suspect that **playItemAtIndex** need some modification like [#265](https://github.com/muhku/FreeStreamer/pull/265)\r\n"}},"public":true,"created_at":"2017-07-07T12:44:13Z"},{"id":"6211721899","type":"IssueCommentEvent","actor":{"id":15805487,"login":"commando24","display_login":"commando24","gravatar_id":"","url":"https://api.github.com/users/commando24","avatar_url":"https://avatars.githubusercontent.com/u/15805487?"},"repo":{"id":2514500,"name":"muhku/FreeStreamer","url":"https://api.github.com/repos/muhku/FreeStreamer"},"payload":{"action":"created","issue":{"url":"https://api.github.com/repos/muhku/FreeStreamer/issues/223","repository_url":"https://api.github.com/repos/muhku/FreeStreamer","labels_url":"https://api.github.com/repos/muhku/FreeStreamer/issues/223/labels{/name}","comments_url":"https://api.github.com/repos/muhku/FreeStreamer/issues/223/comments","events_url":"https://api.github.com/repos/muhku/FreeStreamer/issues/223/events","html_url":"https://github.com/muhku/FreeStreamer/issues/223","id":118192852,"number":223,"title":"AVAudioSession.mm:697: -[AVAudioSession setActive:withOptions:error:]","user":{"login":"ldjhust","id":3424674,"avatar_url":"https://avatars1.githubusercontent.com/u/3424674?v=3","gravatar_id":"","url":"https://api.github.com/users/ldjhust","html_url":"https://github.com/ldjhust","followers_url":"https://api.github.com/users/ldjhust/followers","following_url":"https://api.github.com/users/ldjhust/following{/other_user}","gists_url":"https://api.github.com/users/ldjhust/gists{/gist_id}","starred_url":"https://api.github.com/users/ldjhust/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ldjhust/subscriptions","organizations_url":"https://api.github.com/users/ldjhust/orgs","repos_url":"https://api.github.com/users/ldjhust/repos","events_url":"https://api.github.com/users/ldjhust/events{/privacy}","received_events_url":"https://api.github.com/users/ldjhust/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2015-11-21T12:07:22Z","updated_at":"2017-07-07T12:20:32Z","closed_at":"2016-01-05T11:57:49Z","body":"I met this error when I switch to the next song:\n\n[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.\n\nhere is my switch code:\n- (void)nextSong {\n  // 停止正在播放的歌曲\n  [audioStream_ stop];\n  \n  // 初始化歌曲\n  [backgroundView_ songInfoInitial];\n  // 播放歌曲\n  [self playSong];\n  }\n\ncan somebody help me ? very thank you\n"},"comment":{"url":"https://api.github.com/repos/muhku/FreeStreamer/issues/comments/313666364","html_url":"https://github.com/muhku/FreeStreamer/issues/223#issuecomment-313666364","issue_url":"https://api.github.com/repos/muhku/FreeStreamer/issues/223","id":313666364,"user":{"login":"commando24","id":15805487,"avatar_url":"https://avatars0.githubusercontent.com/u/15805487?v=3","gravatar_id":"","url":"https://api.github.com/users/commando24","html_url":"https://github.com/commando24","followers_url":"https://api.github.com/users/commando24/followers","following_url":"https://api.github.com/users/commando24/following{/other_user}","gists_url":"https://api.github.com/users/commando24/gists{/gist_id}","starred_url":"https://api.github.com/users/commando24/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/commando24/subscriptions","organizations_url":"https://api.github.com/users/commando24/orgs","repos_url":"https://api.github.com/users/commando24/repos","events_url":"https://api.github.com/users/commando24/events{/privacy}","received_events_url":"https://api.github.com/users/commando24/received_events","type":"User","site_admin":false},"created_at":"2017-07-07T12:20:32Z","updated_at":"2017-07-07T12:20:32Z","body":"@muhku i am still having this issue.\r\ni am using FSAudioController with playlist in which i have set configuration with automaticAudioSessionHandlingEnabled to true."}},"public":true,"created_at":"2017-07-07T12:20:32Z"},{"id":"6210532156","type":"IssueCommentEvent","actor":{"id":15805487,"login":"commando24","display_login":"commando24","gravatar_id":"","url":"https://api.github.com/users/commando24","avatar_url":"https://avatars.githubusercontent.com/u/15805487?"},"repo":{"id":2514500,"name":"muhku/FreeStreamer","url":"https://api.github.com/repos/muhku/FreeStreamer"},"payload":{"action":"created","issue":{"url":"https://api.github.com/repos/muhku/FreeStreamer/issues/259","repository_url":"https://api.github.com/repos/muhku/FreeStreamer","labels_url":"https://api.github.com/repos/muhku/FreeStreamer/issues/259/labels{/name}","comments_url":"https://api.github.com/repos/muhku/FreeStreamer/issues/259/comments","events_url":"https://api.github.com/repos/muhku/FreeStreamer/issues/259/events","html_url":"https://github.com/muhku/FreeStreamer/pull/259","id":135375508,"number":259,"title":"Issue #258: Make maxRetryCount public","user":{"login":"PatrikBillgren","id":1339530,"avatar_url":"https://avatars0.githubusercontent.com/u/1339530?v=3","gravatar_id":"","url":"https://api.github.com/users/PatrikBillgren","html_url":"https://github.com/PatrikBillgren","followers_url":"https://api.github.com/users/PatrikBillgren/followers","following_url":"https://api.github.com/users/PatrikBillgren/following{/other_user}","gists_url":"https://api.github.com/users/PatrikBillgren/gists{/gist_id}","starred_url":"https://api.github.com/users/PatrikBillgren/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/PatrikBillgren/subscriptions","organizations_url":"https://api.github.com/users/PatrikBillgren/orgs","repos_url":"https://api.github.com/users/PatrikBillgren/repos","events_url":"https://api.github.com/users/PatrikBillgren/events{/privacy}","received_events_url":"https://api.github.com/users/PatrikBillgren/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2016-02-22T10:21:50Z","updated_at":"2017-07-07T08:52:04Z","closed_at":"2016-02-22T11:35:10Z","pull_request":{"url":"https://api.github.com/repos/muhku/FreeStreamer/pulls/259","html_url":"https://github.com/muhku/FreeStreamer/pull/259","diff_url":"https://github.com/muhku/FreeStreamer/pull/259.diff","patch_url":"https://github.com/muhku/FreeStreamer/pull/259.patch"},"body":"Hello!\n\nMade this property public and put MainThread-asserts on the getter and setter.\n\nIt should be possible to put this property in the Configuration as well if you'd want to?\n"},"comment":{"url":"https://api.github.com/repos/muhku/FreeStreamer/issues/comments/313625928","html_url":"https://github.com/muhku/FreeStreamer/pull/259#issuecomment-313625928","issue_url":"https://api.github.com/repos/muhku/FreeStreamer/issues/259","id":313625928,"user":{"login":"commando24","id":15805487,"avatar_url":"https://avatars0.githubusercontent.com/u/15805487?v=3","gravatar_id":"","url":"https://api.github.com/users/commando24","html_url":"https://github.com/commando24","followers_url":"https://api.github.com/users/commando24/followers","following_url":"https://api.github.com/users/commando24/following{/other_user}","gists_url":"https://api.github.com/users/commando24/gists{/gist_id}","starred_url":"https://api.github.com/users/commando24/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/commando24/subscriptions","organizations_url":"https://api.github.com/users/commando24/orgs","repos_url":"https://api.github.com/users/commando24/repos","events_url":"https://api.github.com/users/commando24/events{/privacy}","received_events_url":"https://api.github.com/users/commando24/received_events","type":"User","site_admin":false},"created_at":"2017-07-07T08:52:04Z","updated_at":"2017-07-07T08:52:04Z","body":"@muhku is it's done ?"}},"public":true,"created_at":"2017-07-07T08:52:04Z"},{"id":"6209228359","type":"WatchEvent","actor":{"id":3031611,"login":"lannik","display_login":"lannik","gravatar_id":"","url":"https://api.github.com/users/lannik","avatar_url":"https://avatars.githubusercontent.com/u/3031611?"},"repo":{"id":48923701,"name":"phimage/CallbackURLKit","url":"https://api.github.com/repos/phimage/CallbackURLKit"},"payload":{"action":"started"},"public":true,"created_at":"2017-07-07T03:22:16Z"},{"id":"6204090972","type":"WatchEvent","actor":{"id":219689,"login":"lexrus","display_login":"lexrus","gravatar_id":"","url":"https://api.github.com/users/lexrus","avatar_url":"https://avatars.githubusercontent.com/u/219689?"},"repo":{"id":77055859,"name":"weixin/WeSketch","url":"https://api.github.com/repos/weixin/WeSketch"},"payload":{"action":"started"},"public":true,"created_at":"2017-07-06T13:30:50Z","org":{"id":14183739,"login":"weixin","gravatar_id":"","url":"https://api.github.com/orgs/weixin","avatar_url":"https://avatars.githubusercontent.com/u/14183739?"}},{"id":"6202669694","type":"ForkEvent","actor":{"id":8609851,"login":"lookingstars","display_login":"lookingstars","gravatar_id":"","url":"https://api.github.com/users/lookingstars","avatar_url":"https://avatars.githubusercontent.com/u/8609851?"},"repo":{"id":88714127,"name":"ksvc/KSYMediaEditorKit_iOS","url":"https://api.github.com/repos/ksvc/KSYMediaEditorKit_iOS"},"payload":{"forkee":{"id":96414822,"name":"KSYMediaEditorKit_iOS","full_name":"lookingstars/KSYMediaEditorKit_iOS","owner":{"login":"lookingstars","id":8609851,"avatar_url":"https://avatars1.githubusercontent.com/u/8609851?v=3","gravatar_id":"","url":"https://api.github.com/users/lookingstars","html_url":"https://github.com/lookingstars","followers_url":"https://api.github.com/users/lookingstars/followers","following_url":"https://api.github.com/users/lookingstars/following{/other_user}","gists_url":"https://api.github.com/users/lookingstars/gists{/gist_id}","starred_url":"https://api.github.com/users/lookingstars/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/lookingstars/subscriptions","organizations_url":"https://api.github.com/users/lookingstars/orgs","repos_url":"https://api.github.com/users/lookingstars/repos","events_url":"https://api.github.com/users/lookingstars/events{/privacy}","received_events_url":"https://api.github.com/users/lookingstars/received_events","type":"User","site_admin":false},"private":false,"html_url":"https://github.com/lookingstars/KSYMediaEditorKit_iOS","description":"金山云短视频编辑SDK iOS版本. Video editor SDK powered by KSYUN, which makes it easy to capture, create, view and share your clips and playback anywhere.","fork":true,"url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS","forks_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/forks","keys_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/keys{/key_id}","collaborators_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/collaborators{/collaborator}","teams_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/teams","hooks_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/hooks","issue_events_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/issues/events{/number}","events_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/events","assignees_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/assignees{/user}","branches_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/branches{/branch}","tags_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/tags","blobs_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/git/blobs{/sha}","git_tags_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/git/tags{/sha}","git_refs_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/git/refs{/sha}","trees_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/git/trees{/sha}","statuses_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/statuses/{sha}","languages_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/languages","stargazers_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/stargazers","contributors_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/contributors","subscribers_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/subscribers","subscription_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/subscription","commits_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/commits{/sha}","git_commits_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/git/commits{/sha}","comments_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/comments{/number}","issue_comment_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/issues/comments{/number}","contents_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/contents/{+path}","compare_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/compare/{base}...{head}","merges_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/merges","archive_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/{archive_format}{/ref}","downloads_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/downloads","issues_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/issues{/number}","pulls_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/pulls{/number}","milestones_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/milestones{/number}","notifications_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/notifications{?since,all,participating}","labels_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/labels{/name}","releases_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/releases{/id}","deployments_url":"https://api.github.com/repos/lookingstars/KSYMediaEditorKit_iOS/deployments","created_at":"2017-07-06T09:46:49Z","updated_at":"2017-07-06T09:46:47Z","pushed_at":"2017-07-06T08:43:04Z","git_url":"git://github.com/lookingstars/KSYMediaEditorKit_iOS.git","ssh_url":"git@github.com:lookingstars/KSYMediaEditorKit_iOS.git","clone_url":"https://github.com/lookingstars/KSYMediaEditorKit_iOS.git","svn_url":"https://github.com/lookingstars/KSYMediaEditorKit_iOS","homepage":"https://v.ksyun.com","size":194271,"stargazers_count":0,"watchers_count":0,"language":null,"has_issues":false,"has_projects":true,"has_downloads":true,"has_wiki":true,"has_pages":false,"forks_count":0,"mirror_url":null,"open_issues_count":0,"forks":0,"open_issues":0,"watchers":0,"default_branch":"master","public":true}},"public":true,"created_at":"2017-07-06T09:46:49Z","org":{"id":16359966,"login":"ksvc","gravatar_id":"","url":"https://api.github.com/orgs/ksvc","avatar_url":"https://avatars.githubusercontent.com/u/16359966?"}}]

```

**Comment by nixzhu** [comment]
Thanks for your test! It's a value merge bug, will be fix later.

**Comment by nixzhu** [comment]
You can use Baby in terminal for now, the shared-baby website is down.

**Comment by nixzhu** [comment]
I just open sourced [SharedBaby](https://github.com/nixzhu/SharedBaby), you may use it in local.

**Comment by CodeEagle** [comment]
already fixed?

**Comment by nixzhu** [comment]
In fact, it was fixed yesterday. But the shared-baby website is down.

**Comment by CodeEagle** [comment]
Still have a little problem
Swift Keyword such as `public` `private` using as property name need  ` .

**Comment by nixzhu** [comment]
You can use *Property Map* to rename them, such as `private: isPrivate, public: isPublic`.

**Comment by CodeEagle** [comment]
okok
